# Generated by Django 3.2.3 on 2021-06-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sekolah',
            options={'verbose_name_plural': 'Daftar Sekolah'},
        ),
        migrations.AddField(
            model_name='sekolah',
            name='status',
            field=models.CharField(choices=[('Client', 'client'), ('Demo', 'demo')], default='Client', max_length=10),
        ),
    ]
